apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: mmealxptj-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bae20b1571.p4ws.p3.openshiftapps.com/rhtap/rhtap-qe:cfdd7db61a98f6ba1f5592bed87d9d13a09640e6@sha256:0d604f17b970fae3c68ccec1536c76bef1be6ec0f4363eff86d89f8dfc58dd45
        name: container-image  
